In [3]:
import pprint
import scipy
import scipy.linalg  
import numpy as np

A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])  # From the Wikipedia Article on QR Decomposition
Q, R = scipy.linalg.qr(A)

pprint.pprint(A)
pprint.pprint(Q)
pprint.pprint(R)

array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])
